from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('',views.Dashboard,name='Dashboard'),
    path('Search/',views.Search,name='Search'),
    path('DigitalPersonalLoan/',views.Digitalploan,name='Digitalploan'),
    path('DigitalBusinessLoan/',views.Digitalbloan,name='Digitalbloan'),
    path('PremiumPersonalLoan/',views.Premiumploan, name='Premiumploan'),
    path('PremiumBusinessLoan/',views.Premiumbloan, name='Premiumbloan'),
    path('Customers/',views.Customers, name='Customers'),
    path('Createaccount/',views.Createaccount, name='Createaccount'),
    path('Cardoffer/',views.Cardoffer, name='Cardoffer'),
    path('Specialoffer/',views.Specialoffer, name='Specialoffer'),
    path('Bumperoffer/',views.Bumperoffer, name='Bumperoffer'),
    path('Staroffer/',views.Staroffer, name='Staroffer'),
    path('Loanlist/',views.Loanlist, name='Loanlist'),
    path('Loanapproved/',views.Loanapproved, name='Loanapproved'),
    path('Loanreapply/',views.Loanreapply, name='Loanreapply'),
    path('Loanquery/',views.Loanquery, name='Loanquery'),
    path('Loanrejected/',views.Loanrejected, name='Loanrejected'),
    path('Marvelmembershipcard/',views.Marvelcard, name='Marvelcard'),
    path('Universalmembershipcard/',views.Universalcard, name='Universalcard'),
    path('Customerreferrals/',views.Customerreferrals, name='Customerreferrals'),
    path('Allleads/',views.Allleads, name='Allleads'),
    path('Personalleads/',views.Personalleads, name='Personalleads'),
    path('Businessleads/',views.Businessleads, name='Businessleads'),
    path('Customerleads/', views.Customerleads, name='Customerleads'),
    path('GSTData/', views.GSTData, name='GSTData'),
    path('Bank/', views.Bank, name='Bank'),
    path('Applybank/', views.Applybank, name='Applybank'),
    path('Currentopenning/', views.Currentopenning, name='Currentopenning'),
    path('Careerenquiry/', views.Careerenquiry, name='Careerenquiry'),
    path('BulkOTPs/', views.BulkOTPs, name='BulkOTPs'),
    path('SupportReq/', views.SupportReq, name='SupportReq'),
    path('ConntactEnq/', views.ConntactEnq, name='ConntactEnq'),
    path('NewsletterSub/', views.NewsletterSub, name='NewsletterSub'),
    path('SentOTPs/', views.SentOTPs, name='SentOTPs'),
    path('Importantupdate/', views.Importantupdate, name='Importantupdate'),
    path('SMSMessages/', views.SMSMessages, name='SMSMessages'),
    path('SiteSettings/', views.SiteSettings, name='SiteSettings'),
    path('Accountmessage/', views.Accountmessage, name='Accountmessage'),
]