# Generated by Django 4.2.1 on 2023-05-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persontype', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('require_loan_amount', models.CharField(max_length=10)),
                ('cibil_score', models.CharField(max_length=10)),
                ('monthly_income', models.CharField(max_length=10)),
                ('monthly_emi_you_pay', models.CharField(max_length=10)),
                ('loan_purpose', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('emi_tenure', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('otp', models.CharField(default=0, max_length=4)),
                ('phone', models.CharField(max_length=20)),
                ('max_otp_try', models.IntegerField(default=3)),
            ],
        ),
    ]
